<?php

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setUsingCache(true)
    ->setRules([
        '@PSR2'                                         => true,
        'align_multiline_comment'                       => true,
        'array_indentation'                             => true,
        'array_syntax'                                  => ['syntax' => 'short'],
        'binary_operator_spaces'                        => true,
        'blank_line_after_namespace'                    => true,
        'blank_line_after_opening_tag'                  => false,
        'blank_line_before_statement'                   => [
            'statements' => ['return', 'try'],
        ],
        'braces'                                        => true,
        'cast_spaces'                                   => true,
        'class_attributes_separation'                   => [
            'elements' => ['method', 'property'],
        ],
        'class_definition'                              => true,
        'class_keyword_remove'                          => false,
        'combine_consecutive_issets'                    => true,
        'combine_consecutive_unsets'                    => true,
        'compact_nullable_typehint'                     => true,
        'concat_space'                                  => ['spacing' => 'one'],
        'declare_equal_normalize'                       => true,
        'doctrine_annotation_array_assignment'          => true,
        'doctrine_annotation_braces'                    => true,
        'doctrine_annotation_indentation'               => true,
        'doctrine_annotation_spaces'                    => [
            'before_array_assignments_equals' => false,
            'after_array_assignments_equals'  => false,
        ],
        'elseif'                                        => true,
        'escape_implicit_backslashes'                   => true,
        'explicit_indirect_variable'                    => true,
        'explicit_string_variable'                      => true,
        'final_class'                                   => false,
        'full_opening_tag'                              => true,
        'function_declaration'                          => true,
        'function_typehint_space'                       => true,
        'general_phpdoc_annotation_remove'              => [
            'annotations' => ['author'],
        ],
        'include'                                       => true,
        'indentation_type'                              => true,
        'linebreak_after_opening_tag'                   => true,
        'list_syntax'                                   => ['syntax' => 'short'],
        'lowercase_cast'                                => true,
        'lowercase_constants'                           => true,
        'lowercase_keywords'                            => true,
        'lowercase_static_reference'                    => true,
        'magic_constant_casing'                         => true,
        'magic_method_casing'                           => true,
        'method_argument_space'                         => true,
        'method_chaining_indentation'                   => true,
        'multiline_comment_opening_closing'             => true,
        'multiline_whitespace_before_semicolons'        => true,
        'native_function_casing'                        => true,
        'native_function_type_declaration_casing'       => true,
        'new_with_braces'                               => false,
        'no_binary_string'                              => true,
        'no_blank_lines_after_class_opening'            => true,
        'no_blank_lines_after_phpdoc'                   => true,
        'no_closing_tag'                                => true,
        'no_empty_phpdoc'                               => true,
        'no_empty_statement'                            => true,
        'no_extra_blank_lines'                          => [
            'tokens' => ['continue', 'curly_brace_block', 'extra', 'parenthesis_brace_block', 'return', 'square_brace_block', 'throw', 'use', 'use_trait', 'switch', 'case', 'default']
        ],
        'no_leading_import_slash'                       => true,
        'no_leading_namespace_whitespace'               => true,
        'no_mixed_echo_print'                           => true,
        'no_multiline_whitespace_around_double_arrow'   => true,
        'no_null_property_initialization'               => true,
        'no_short_bool_cast'                            => true,
        'no_short_echo_tag'                             => true,
        'no_singleline_whitespace_before_semicolons'    => true,
        'no_spaces_after_function_name'                 => true,
        'no_spaces_around_offset'                       => true,
        'no_spaces_inside_parenthesis'                  => true,
        'no_superfluous_elseif'                         => true,
        'no_trailing_comma_in_list_call'                => true,
        'no_trailing_comma_in_singleline_array'         => true,
        'no_trailing_whitespace'                        => true,
        'no_trailing_whitespace_in_comment'             => true,
        'no_unneeded_control_parentheses'               => true,
        'no_unneeded_curly_braces'                      => true,
        'no_unneeded_final_method'                      => true,
        'no_unused_imports'                             => true,
        'no_useless_else'                               => true,
        'no_useless_return'                             => true,
        'no_whitespace_before_comma_in_array'           => true,
        'no_whitespace_in_blank_line'                   => true,
        'normalize_index_brace'                         => true,
        'not_operator_with_successor_space'             => false,
        'object_operator_without_whitespace'            => true,
        'ordered_imports'                               => true,
        'php_unit_fqcn_annotation'                      => true,
        'php_unit_method_casing'                        => true,
        'php_unit_strict'                               => false, // TODO: enable later after assertSame is in place
        'phpdoc_add_missing_param_annotation'           => true,
        'phpdoc_align'                                  => true,
        'phpdoc_indent'                                 => true,
        'phpdoc_inline_tag'                             => true,
        'phpdoc_no_access'                              => true,
        'phpdoc_no_alias_tag'                           => true,
        'phpdoc_no_empty_return'                        => true,
        'phpdoc_no_package'                             => true,
        'phpdoc_order'                                  => true,
        'phpdoc_scalar'                                 => true,
        'phpdoc_separation'                             => true,
        'phpdoc_single_line_var_spacing'                => true,
        'phpdoc_summary'                                => true,
        'phpdoc_to_comment'                             => false,
        'phpdoc_trim'                                   => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types'                                  => true,
        'phpdoc_types_order'                            => true,
        'phpdoc_var_without_name'                       => true,
        'protected_to_private'                          => true,
        'psr4'                                          => true,
        'return_assignment'                             => true,
        'semicolon_after_instruction'                   => true,
        'short_scalar_cast'                             => true,
        'simple_to_complex_string_variable'             => true,
        'simplified_null_return'                        => true,
        'single_blank_line_before_namespace'            => true,
        'single_line_after_imports'                     => true,
        'single_line_comment_style'                     => true,
        'single_quote'                                  => true,
        'switch_case_semicolon_to_colon'                => true,
        'switch_case_space'                             => true,
        'ternary_operator_spaces'                       => true,
        'trailing_comma_in_multiline_array'             => true,
        'trim_array_spaces'                             => true,
        'unary_operator_spaces'                         => true,
        'visibility_required'                           => true,
        'whitespace_after_comma_in_array'               => true,
        'yoda_style'                                    => false,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->notPath('bootstrap/cache')
            ->notPath('storage')
            ->notPath('vendor')
            ->notPath('node_modules')
            ->notPath('bower_components')
            ->in(__DIR__ . '/app')
            ->in(__DIR__ . '/config')
            ->in(__DIR__ . '/database')
            ->in(__DIR__ . '/resources')
            ->in(__DIR__ . '/routes')
            ->name('*.php')
            ->notName('*.blade.php')
            ->ignoreDotFiles(true)
            ->ignoreVCS(true)
    );